name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Docker test
      run: |
        docker image pull debian:latest
        
    - name: Docker build
      run: |
        docker-compose up -d
        
    - name: Run tests in container
      run: |
        docker-compose exec web python3 manage.py test books.tests.test_models books.tests.test_serializers books.tests.test_viewsets