name: Django Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
  
jobs:
  build:

    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test books.tests.test_models books.tests.test_serializers books.tests.test_viewsets
        coverage report
    - name: Django testing
      run: |
        python3 manage.py test books.tests.test_models books.tests.test_serializers books.tests.test_viewsets
